package Vista;

import java.awt.Color;
import java.awt.Container;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 * Ventana de interfaz encargada de la eliminación de jugadores del sistema.
 * Permite seleccionar un jugador registrado mediante un desplegable y proceder con su baja.
 * * @author Cristiangm05
 */
public class EliminarJugador extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EliminarJugador.class.getName());

    /**
     * Constructor que inicializa los componentes de la vista, configura el diseño visual,
     * el fondo personalizado y carga el icono de la ventana.
     */
    public EliminarJugador() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new java.awt.Color(20, 25, 40));
        configurarFondoVentana("/img/fondoEliminarJugador.jpg");
        configurarComboBox();
        
        Image logo = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logoEliminar.png"));
        this.setIconImage(logo);
    }

    /**
     * Aplica estilos personalizados al JComboBox de selección de jugadores para integrarlo
     * mejor con el diseño estético de la ventana.
     */
    public final void configurarComboBox() {
        comboEliminar.setOpaque(false);
        comboEliminar.setBorder(BorderFactory.createEmptyBorder());

        ((javax.swing.JComponent) comboEliminar.getRenderer()).setOpaque(false);
        comboEliminar.setForeground(Color.black);
    }

    /**
     * Implementa un sistema de capas (JLayeredPane) para superponer un panel de fondo 
     * personalizado sobre el contenido estándar de la ventana.
     * * @param rutaImagen String con la ruta del recurso de la imagen de fondo.
     */
    public final void configurarFondoVentana(String rutaImagen) {
        JLayeredPane layeredPane = new JLayeredPane();
        layeredPane.setPreferredSize(this.getSize());

        PanelFondo panelFondo = new PanelFondo(rutaImagen);
        panelFondo.setBounds(0, 0, this.getWidth(), this.getHeight());

        Container contentPane = this.getContentPane();
        if (contentPane instanceof JPanel) {
            ((JPanel) contentPane).setOpaque(false);
        }
        
        // Capa 0: Fondo, Capa 1: Componentes (botones, campos)
        layeredPane.add(panelFondo, Integer.valueOf(0));
        layeredPane.add(contentPane, Integer.valueOf(1));

        this.setContentPane(layeredPane);

        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        comboEliminar = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("♦️ BAJA DE JUGADORES ♦️");
        setBackground(new java.awt.Color(0, 51, 51));
        setResizable(false);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonVolverAlMenuEliminar.png"))); // NOI18N
        btnCerrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setFocusPainted(false);

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonEliminar.png"))); // NOI18N
        btnBorrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar.setBorderPainted(false);
        btnBorrar.setContentAreaFilled(false);
        btnBorrar.setFocusPainted(false);

        comboEliminar.setBackground(new java.awt.Color(255, 255, 255));
        comboEliminar.setForeground(new java.awt.Color(0, 0, 0));
        comboEliminar.setMaximumRowCount(20);
        comboEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elegir Jugador" }));
        comboEliminar.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(btnCerrar)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comboEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(comboEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBorrar)
                    .addComponent(btnCerrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EliminarJugador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBorrar;
    public javax.swing.JButton btnCerrar;
    public javax.swing.JComboBox<String> comboEliminar;
    // End of variables declaration//GEN-END:variables
}
