package Vista;

import java.awt.Container;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 * Ventana de interfaz encargada de mostrar el historial de partidas del casino.
 * Permite visualizar los resultados anteriores y estadísticas almacenadas en la base de datos.
 * * @author Cristiangm05
 */
public class HistorialPartidas extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HistorialPartidas.class.getName());

    /**
     * Constructor que inicializa los componentes de la vista, configura el diseño visual,
     * el fondo personalizado y carga el icono representativo de las estadísticas.
     */
    public HistorialPartidas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new java.awt.Color(0, 51, 51));
        configurarFondoVentana("/img/fondoEstadisticas.png");
        
        Image logo = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logoEstadisticas.png"));
        this.setIconImage(logo);
    }

    /**
     * Implementa un sistema de capas (JLayeredPane) para superponer un panel de fondo 
     * personalizado sobre el contenido de la ventana, permitiendo que los componentes 
     * sobrepuestos mantengan transparencia.
     * * @param rutaImagen String con la ruta del recurso de la imagen de fondo.
     */
    public final void configurarFondoVentana(String rutaImagen) {
        JLayeredPane layeredPane = new JLayeredPane();
        layeredPane.setPreferredSize(this.getSize());

        PanelFondo panelFondo = new PanelFondo(rutaImagen);
        panelFondo.setBounds(0, 0, this.getWidth(), this.getHeight());

        Container contentPane = this.getContentPane();
        if (contentPane instanceof JPanel) {
            ((JPanel) contentPane).setOpaque(false);
        }
        
        // Capa 0: Imagen de fondo, Capa 1: Contenido (tablas y botones)
        layeredPane.add(panelFondo, Integer.valueOf(0));
        layeredPane.add(contentPane, Integer.valueOf(1));

        this.setContentPane(layeredPane);

        this.revalidate();
        this.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolverHistorial = new javax.swing.JButton();
        panelScroll = new javax.swing.JScrollPane();
        tblEstadisticas = new javax.swing.JTable();
        lblPartidasTotales = new javax.swing.JLabel();
        lblApuestaMax = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("🏆 HISTORIAL Y ESTADÍSTICAS 🏆");
        setBackground(new java.awt.Color(0, 51, 51));
        setResizable(false);

        btnVolverHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonVolverAlMenuEstadisticas.png"))); // NOI18N
        btnVolverHistorial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        btnVolverHistorial.setBorderPainted(false);
        btnVolverHistorial.setContentAreaFilled(false);
        btnVolverHistorial.setFocusPainted(false);

        panelScroll.setBackground(new java.awt.Color(51, 51, 51));
        panelScroll.setForeground(new java.awt.Color(255, 255, 255));

        tblEstadisticas.setBackground(new java.awt.Color(51, 51, 51));
        tblEstadisticas.setForeground(new java.awt.Color(255, 255, 255));
        tblEstadisticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Partida", "Fecha y Hora", "Jugador", "Apuesta", "Resultado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEstadisticas.setFillsViewportHeight(true);
        panelScroll.setViewportView(tblEstadisticas);

        lblPartidasTotales.setBackground(new java.awt.Color(0, 153, 102));
        lblPartidasTotales.setForeground(new java.awt.Color(255, 255, 255));
        lblPartidasTotales.setText("⭐ Partidas Totales Jugadas:");

        lblApuestaMax.setBackground(new java.awt.Color(0, 153, 102));
        lblApuestaMax.setForeground(new java.awt.Color(255, 255, 255));
        lblApuestaMax.setText("💰 Mayor Apuesta Registrada:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApuestaMax, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPartidasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVolverHistorial))
                    .addComponent(panelScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(panelScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVolverHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblPartidasTotales, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblApuestaMax, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HistorialPartidas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnVolverHistorial;
    public javax.swing.JLabel lblApuestaMax;
    public javax.swing.JLabel lblPartidasTotales;
    private javax.swing.JScrollPane panelScroll;
    private javax.swing.JTable tblEstadisticas;
    // End of variables declaration//GEN-END:variables

    // Método puente para que el controlador pueda rellenar la tabla de forma segura
    public javax.swing.table.DefaultTableModel getModeloTabla() {
        return (javax.swing.table.DefaultTableModel) tblEstadisticas.getModel();
    }
}
