package Vista;

import java.awt.Container;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 * Ventana que actúa como punto de entrada principal para el usuario en la aplicación.
 * Proporciona acceso a las distintas secciones del casino como la mesa de juego, 
 * registro, gestión de jugadores e historial.
 * * @author Cristiangm05
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Constructor que inicializa los componentes de la interfaz, centra la ventana
     * en pantalla, aplica el fondo personalizado y establece el icono de la aplicación.
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new java.awt.Color(15, 32, 67));
        configurarFondoVentana("/img/fondoMenuPrincipal.jpg");
        
        Image logo = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logoMenu.png"));
        this.setIconImage(logo);
    }
    
    /**
     * Configura un sistema de capas (JLayeredPane) para gestionar la superposición
     * visual entre la imagen de fondo y los botones interactivos del menú.
     * * @param rutaImagen La ruta al recurso de la imagen que se usará como fondo.
     */
    public final void configurarFondoVentana(String rutaImagen) {
        JLayeredPane layeredPane = new JLayeredPane();
        layeredPane.setPreferredSize(this.getSize());

        // Panel de fondo que se sitúa en la capa inferior
        PanelFondo panelFondo = new PanelFondo(rutaImagen);
        panelFondo.setBounds(0, 0, this.getWidth(), this.getHeight());

        // Preparación del contenedor para permitir transparencia sobre el fondo
        Container contentPane = this.getContentPane();
        if (contentPane instanceof JPanel) {
            ((JPanel) contentPane).setOpaque(false);
        }
        
        // Apilado de capas: Fondo en nivel 0, Contenido (botones/menus) en nivel 1
        layeredPane.add(panelFondo, Integer.valueOf(0));
        layeredPane.add(contentPane, Integer.valueOf(1));

        this.setContentPane(layeredPane);

        // Refresco de la interfaz para aplicar los cambios visuales
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloMenuPrincipal = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        btnEliminarJugador = new javax.swing.JButton();
        btnSalirJuego = new javax.swing.JButton();
        btnRegistrarVIP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blackjack Casino - Menú Principal");
        setPreferredSize(new java.awt.Dimension(750, 800));
        setResizable(false);

        tituloMenuPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        tituloMenuPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        tituloMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tituloMenuPrincipal.png"))); // NOI18N

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonRegistrarJugador.png"))); // NOI18N
        btnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setFocusPainted(false);

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonIniciarPartida.png"))); // NOI18N
        btnJugar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnJugar.setBorderPainted(false);
        btnJugar.setContentAreaFilled(false);
        btnJugar.setFocusPainted(false);

        btnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonEstadisticas.png"))); // NOI18N
        btnHistorial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnHistorial.setBorderPainted(false);
        btnHistorial.setContentAreaFilled(false);
        btnHistorial.setFocusPainted(false);

        btnEliminarJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonEliminarJugador.png"))); // NOI18N
        btnEliminarJugador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnEliminarJugador.setBorderPainted(false);
        btnEliminarJugador.setContentAreaFilled(false);
        btnEliminarJugador.setFocusPainted(false);

        btnSalirJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonSalir.png"))); // NOI18N
        btnSalirJuego.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnSalirJuego.setBorderPainted(false);
        btnSalirJuego.setContentAreaFilled(false);
        btnSalirJuego.setFocusPainted(false);

        btnRegistrarVIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonRegistrarVip.png"))); // NOI18N
        btnRegistrarVIP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btnRegistrarVIP.setBorderPainted(false);
        btnRegistrarVIP.setContentAreaFilled(false);
        btnRegistrarVIP.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btnRegistrarVIP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(btnSalirJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12))))
                    .addComponent(tituloMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(tituloMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrarVIP, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalirJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEliminarJugador;
    public javax.swing.JButton btnHistorial;
    public javax.swing.JButton btnJugar;
    public javax.swing.JButton btnRegistrar;
    public javax.swing.JButton btnRegistrarVIP;
    public javax.swing.JButton btnSalirJuego;
    public javax.swing.JLabel tituloMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
