package Vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;

/**
 * Ventana de interfaz para el registro de nuevos jugadores en el casino.
 * Permite gestionar tanto el registro estándar como el registro VIP, ajustando
 * dinámicamente los estilos visuales según el modo seleccionado.
 * * @author Cristiangm05
 */
public class RegistrarJugador extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrarJugador.class.getName());

    /**
     * Constructor que inicializa los componentes de la vista y configura
     * el comportamiento inicial del campo de texto principal.
     */
    public RegistrarJugador() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new java.awt.Color(53, 4, 12));
        configurarCampoNombre();
        
        // Listener para asegurar el foco en el campo de texto al hacer clic en el contenedor
        txtNombre.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                txtNombre.requestFocusInWindow();
            }
        });
    }

    /**
     * Implementa un sistema de capas (JLayeredPane) para superponer un panel de fondo 
     * personalizado sobre el contenido de la ventana.
     * * @param rutaImagen Ruta al recurso de imagen que servirá de fondo.
     */
    public final void configurarFondoVentana(String rutaImagen) {
        JLayeredPane layeredPane = new JLayeredPane();
        layeredPane.setPreferredSize(this.getSize());

        PanelFondo panelFondo = new PanelFondo(rutaImagen);
        panelFondo.setBounds(0, 0, this.getWidth(), this.getHeight());

        Container contentPane = this.getContentPane();
        if (contentPane instanceof JPanel) {
            ((JPanel) contentPane).setOpaque(false);
        }
        
        layeredPane.add(panelFondo, Integer.valueOf(0));
        layeredPane.add(contentPane, Integer.valueOf(1));

        this.setContentPane(layeredPane);
        this.revalidate();
        this.repaint();
    }

    /**
     * Adapta la interfaz de usuario dependiendo de si el registro es para un 
     * usuario estándar o un usuario VIP, cambiando iconos, colores y fondos.
     * * @param esVip True para activar la configuración VIP, false para estándar.
     */
    public void configurarModo(boolean esVip) {
        if (esVip) {
            this.setTitle("♦ REGISTRO VIP ♦");
            this.getContentPane().setBackground(new java.awt.Color(102, 102, 0));
            
            ImageIcon iconoVip = new ImageIcon(getClass().getResource("/img/tituloRegistrarJugadorVIP.png"));
            tituloRegistrarJugador.setIcon(iconoVip);
            
            ImageIcon iconoLabelVip = new ImageIcon(getClass().getResource("/img/labelRegistrarJugadorVIP.png"));
            jLabel2.setIcon(iconoLabelVip);
            
            configurarFondoVentana("/img/fondoRegistrarJugadorVip.jpg");
            Image logoVip = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logoRegistrarVip.png"));
            this.setIconImage(logoVip);
            
        } else {
            this.setTitle("♦ REGISTRO ESTÁNDAR ♦");
            configurarFondoVentana("/img/fondoRegistrarJugador.jpg");
            Image logo = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logoRegistrar.png"));
            this.setIconImage(logo);
        }
    }

    /**
     * Personaliza el campo de texto de entrada para el nombre, eliminando bordes 
     * estándar y ajustándolo visualmente dentro de su contenedor de imagen.
     */
    public final void configurarCampoNombre() {
        lblCampoRegJugImg.setLayout(new BorderLayout());

        txtNombre.setOpaque(false);
        txtNombre.setBorder(BorderFactory.createEmptyBorder(10, 55, 10, 30));

        txtNombre.setForeground(Color.WHITE);
        txtNombre.setCaretColor(Color.WHITE);
        txtNombre.setFont(new Font("Serif", Font.BOLD, 18));

        lblCampoRegJugImg.add(txtNombre, BorderLayout.CENTER);
        txtNombre.setBackground(new Color(0, 0, 0, 0));

        lblCampoRegJugImg.revalidate();
        lblCampoRegJugImg.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloRegistrarJugador = new javax.swing.JLabel();
        btnVolverRegistro = new javax.swing.JButton();
        btnGuardarJugador = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panel = new javax.swing.JLayeredPane();
        txtNombre = new javax.swing.JTextField();
        lblCampoRegJugImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Jugador");
        setBackground(new java.awt.Color(53, 4, 12));
        setPreferredSize(new java.awt.Dimension(500, 625));
        setResizable(false);

        tituloRegistrarJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tituloRegistrarJugador.png"))); // NOI18N

        btnVolverRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonVolverAlMenu.png"))); // NOI18N
        btnVolverRegistro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        btnVolverRegistro.setBorderPainted(false);
        btnVolverRegistro.setContentAreaFilled(false);
        btnVolverRegistro.setFocusPainted(false);

        btnGuardarJugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/botonRegistrar.png"))); // NOI18N
        btnGuardarJugador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardarJugador.setBorderPainted(false);
        btnGuardarJugador.setContentAreaFilled(false);
        btnGuardarJugador.setFocusPainted(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/labelRegistrarJugador.png"))); // NOI18N

        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombre.setBorder(null);

        lblCampoRegJugImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/campoNombreJugador.png"))); // NOI18N

        panel.setLayer(txtNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(lblCampoRegJugImg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblCampoRegJugImg, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblCampoRegJugImg, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVolverRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel2))
                    .addComponent(tituloRegistrarJugador))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloRegistrarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolverRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistrarJugador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGuardarJugador;
    public javax.swing.JButton btnVolverRegistro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblCampoRegJugImg;
    private javax.swing.JLayeredPane panel;
    public javax.swing.JLabel tituloRegistrarJugador;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
